# Start (inclusive) of allowed custom ids. Change these to make NationGen compatible with other mods
# with well-defined Dominions id boundaries. For example, if you want to use a mod which occupies
# custom monster ids up until 6987, set the min.custom.monster.id to 6988. The default values below
# are the entire range of Dominions 6 custom ids per the modding manual.

min.custom.armor.id=300
min.custom.monster.id=5000
min.custom.montag.id=1000
min.custom.nametype.id=170
min.custom.nation.id=150
min.custom.site.id=1700
min.custom.spell.id=1300
min.custom.weapon.id=1000

# End (inclusive) of allowed custom ids. Change these to make NationGen compatible with other mods
# with well-defined Dominions id boundaries. For example, if you want to use a mod which occupies
# custom monster ids starting at 6000, set the max.custom.monster.id to 5999.

max.custom.armor.id=999
max.custom.monster.id=8999
max.custom.montag.id=100000
max.custom.nametype.id=399
max.custom.nation.id=499
max.custom.site.id=3999
max.custom.spell.id=3999
max.custom.weapon.id=3999
